### ISSUE TITLE
Plug does not respond to Homebridge instructions

### ISSUE THREAD

**Issue by blloyd78** [drumfreak/homebridge-tuya-powerstrip#4]
Finally had a chance to re-test this issue.

I have a Tuya-Based plug that has been installed and configured using the eFamilyCloud app. I can power the plug on and off using the supplied app.

I have also installed the homebridge-tuya-powerstrip plugin and added the necessary entries to my config.json. Following reboot, the plug appears in the Home app, and Homebridge correctly reports the power status - on or off.

But... instructions to toggle power are never received by the plug.

**Comment by j3nk216** [comment]
Hey there,

I have a simular problem with my tuya sockets. The status of the outlets is reported correctly to the home app, but I can't control the sockets with the app. 

Have you found a solution for it?

**Comment by blloyd78** [comment]
No. I saw that some of the Tuya plugins had been updated over the past few weeks, so tried again. I still have the same problem - switch status reports correctly, but commands are not sent to the device.
